name: depot_repository
description: Dart package to interact with the Flatex API.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dio: ^5.1.1
  dart_mappable: ^2.0.3
  certificate_pinning_httpclient: ^0.0.3
  logger: ^1.3.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  dart_mappable_builder: ^2.0.2
