name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  biometric_storage: ^4.1.3
  depot_repository:
    path: ../../packages/depot_repository
  logger: ^1.3.0
  shared_preferences: ^2.1.0
  encrypt: ^5.0.1
  dio: ^5.1.1

dev_dependencies:
  very_good_analysis: ^3.1.0
