name: test android emulator

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 */12 * * *'

jobs:
  main:
    name: Test on Android emulator (${{ matrix.api-level }}, ${{ matrix.target}}, ${{matrix.arch}})
    runs-on: buildjet-2vcpu-ubuntu-2204
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        flutter-channel: [stable]
        api-level: [31]
        target: [google_apis]
        arch: [x86_64]

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adbkey
            ~/.android/adbkey.pub
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          arch: ${{ matrix.arch }}
          ram-size: 2048M
          channel: canary
          script: echo "Generated AVD snapshot for caching."

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Preload Flutter artifacts
        run: flutter precache

      - name: Set up Patrol CLI
        run: dart pub global activate patrol_cli

      - name: Generate Gradle wrapper
        run: flutter build apk --debug --flavor=does-not-exist || true

      - name: Start emulator and run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          working-directory: ${{ github.workspace }}/
          arch: ${{ matrix.arch }}
          ram-size: 2048M
          channel: canary
          script: |
            flutter logs &
            patrol test -t integration_test/demo_test.dart
      - name: Upload logcat to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Results for ${{ matrix.api-level }}-${{ matrix.target}}-${{matrix.arch}}.txt
          path: |
            ${{ github.workspace }}/logcat.txt
            ${{ github.workspace }}/test-results
            ${{ github.workspace }}/test-reports
